/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light_Targets.glb 
*/

import React from 'react'
import { useGLTFWithKTX2 } from '../../utils/useGtlfWithkxt2'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/models/Light Room/Light_Targets.glb');


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Design_Work_Hitbox.geometry} material={nodes.Design_Work_Hitbox.material} position={[24.434, 0.649, -1.105]} />
      <mesh geometry={nodes.Design_Work_Hitbox_Anim.geometry} material={nodes.Design_Work_Hitbox_Anim.material} position={[23.345, 1.267, -0.573]} />
    </group>
  )
}

