/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light_Third.glb 
*/

import React from 'react'

import { useGLTFWithKTX2 } from '../../utils/useGtlfWithkxt2'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/models/Light Room/Light_Third.glb')
    const newMaterials = convertMaterialsToBasic(materials, 0.1);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Light_Third_Baked.geometry} material={newMaterials.REAL_third_Baked} position={[24.79, -0.201, 0.173]} />
    </group>
  )
}

