/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light_Targets.glb 
*/

import React, { useRef } from 'react'
import { useGLTFWithKTX2 } from '../../utils/useGtlfWithkxt2'
import * as THREE from 'three'
import gsap from 'gsap'
import { useSidepanelStore } from '../../../stores/sidepanel.store';
import { useNavigate } from 'react-router';

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/models/Light Room/Light_Targets.glb');
  const open = useSidepanelStore((state) => state.open);
  const blackMaterial = new THREE.MeshBasicMaterial({ color: '#000000' })
  const lightDevWork = useRef();
  const navigate = useNavigate()
 
  const animationPairs = [
    { meshRef: lightDevWork, key: 'dev_work' },
  ];
 const handleMouse = (key, isOver) => (event) => {
    event.stopPropagation();
    const object = animationPairs.find(pair => pair.key === key);
    if (object) {
      const scaleValue = isOver ? 1 : 0;
      gsap.to(object.meshRef.current.scale, {
        x: scaleValue,
        y: scaleValue,
        z: scaleValue,
        duration: 0.5,
        ease: "power2.out",
      });
    }
  }


  const handleClick = () => {
    open();
    navigate('/projects')
  }


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Design_Work_Hitbox.geometry}
        visible={false}
        material={nodes.Design_Work_Hitbox.material}
        position={[24.434, 0.649, -1.105]}
        onClick={() => handleClick()}
        onPointerOver={handleMouse('dev_work', true)}
        onPointerOut={handleMouse('dev_work', false)}
      />
      <mesh ref={lightDevWork}
        geometry={nodes.Design_Work_Hitbox_Anim.geometry}
        material={blackMaterial}
        position={[23.345, 1.267, -0.573]} />
    </group>
  )
}

