/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light_Third.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Light_Third.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Light_Third_Baked.geometry} material={materials.REAL_third_Baked} position={[24.79, -0.201, 0.173]} />
    </group>
  )
}

useGLTF.preload('/Light_Third.glb')
