/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light_Fourth.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Light_Fourth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Light_Fourth_Baked.geometry} material={materials.REAL_fourth_Baked} position={[26.632, -0.17, -1.134]} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/Light_Fourth.glb')
