/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light_Second.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Light_Second.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Light_Second_Baked.geometry} material={materials.actual_second_bro_Baked} position={[26.719, 1.498, 1.614]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/Light_Second.glb')
