/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light_First.glb 
*/

import React, { useRef } from 'react'
import { useGLTFWithKTX2 } from '../../utils/useGtlfWithkxt2'
import { convertMaterialsToBasic } from '../../utils/convertToBasic'
import { useVideoTexture } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/models/Light Room/Light_First.glb')

  const newMaterials = convertMaterialsToBasic(materials, 0.1);
   const computerScreenRef = useRef();
  
    const videoTexture = useVideoTexture("/videos/devwork.mp4", {
      crossOrigin: "anonymous",
      muted: true,
      loop: true,
      playsInline: true,
      start: true,
    });
  return (
    <group {...props} dispose={null}>
      <mesh ref={computerScreenRef} geometry={nodes.iPhone_Screen.geometry} material={newMaterials['Computer scrreen']} position={[23.994, 0.734, -1.338]} rotation={[0, -1.193, Math.PI / 2]} />
      <mesh geometry={nodes.Desktop_Screen.geometry} position={[24.377, 0.968, -1.548]} rotation={[-Math.PI / 2, 0, 0]} >
        <meshBasicMaterial
          map={videoTexture}
          color="#f6f6f6"
          toneMapped={false}
        />
      </mesh>
      <mesh geometry={nodes.Light_First_Baked.geometry} material={newMaterials.REAL_first_Baked} position={[23.66, 1.452, -1.692]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

