/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark_First.glb 
*/
import React, { useRef } from 'react'
import { convertMaterialsToBasic } from '../../utils/convertToBasic'
import { useGLTFWithKTX2 } from '../../utils/useGtlfWithkxt2'
import { useVideoTexture } from '@react-three/drei';


export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/models/Dark Room/Dark_First.glb')

  const newMaterials = convertMaterialsToBasic(materials, 0.1);
  const macBookRef = useRef();
  const computerScreenRef = useRef();

  const videoTexture = useVideoTexture("/videos/devwork.mp4", {
    crossOrigin: "anonymous",
    muted: true,
    loop: true,
    playsInline: true,
    start: true,
  });

  return (
    <group {...props} dispose={null}>
      <mesh ref={macBookRef} geometry={nodes.Mac_Screen.geometry} position={[-0.861, 0.815, 0.684]} rotation={[0, 0.523, 0]} >
        <meshBasicMaterial
          map={videoTexture}
          color="#f6f6f6"
          toneMapped={false}
        />
      </mesh>
      <mesh ref={computerScreenRef} geometry={nodes.Computer_Screen.geometry} position={[-0.302, 0.955, 0.647]} rotation={[0, -0.053, 0]} >
        <meshBasicMaterial
          map={videoTexture}
          color="#f6f6f6"
          toneMapped={false}
        />
      </mesh>
      <mesh geometry={nodes.First_Baked.geometry} material={newMaterials.first_real_realfdsa_Baked} position={[-0.231, -0.14, 0.652]} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}
