/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark_Targets.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import gsap from "gsap";
import { useSidepanelStore } from "../../../stores/sidepanel.store";


export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Dark Room/Dark_Targets.glb");
  const whiteMaterial = new THREE.MeshBasicMaterial({ color: 0xffffff, metalness: 0.5, roughness: 0.5 });
  const setVisible = useSidepanelStore((state) => state.setVisible);
  const aboutAnimRef = React.useRef();
  const devWorkAnimRef = React.useRef();

  const animationPairs = [
    { meshRef: aboutAnimRef, key: 'about' },
    { meshRef: devWorkAnimRef, key: 'dev_work' },
  ];

  const handleMouse = (key, isOver) => (event) => {
    event.stopPropagation();
    const object = animationPairs.find(pair => pair.key === key);
    if (object) {
      const scaleValue = isOver ? 1 : 0;
      gsap.to(object.meshRef.current.scale, {
        x: scaleValue,
        y: scaleValue,
        z: scaleValue,
        duration: 0.5,
        ease: "power2.out",
      });
    }
  }

  const handleClick = () => {
    setVisible();
  }


  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.About_Hitbox.geometry}
        material={nodes.About_Hitbox.material}
        visible={false}
        onPointerOver={handleMouse('about', true)}
        onPointerOut={handleMouse('about', false)}
        onClick={handleClick()}
        position={[0.679, 1.571, -1.368]}

      />
      <mesh
        geometry={nodes.About_Hitbox_Anim.geometry}
        material={whiteMaterial}
        scale={0}
        position={[0.679, 1.571, -1.368]}

        ref={aboutAnimRef}
      />
      <mesh
        geometry={nodes.Dev_Work_Hitbox.geometry}
        material={nodes.Dev_Work_Hitbox.material}
        visible={false}
        position={[-0.457, 0.597, 1.021]}
        onClick={handleClick()}
        onPointerOver={handleMouse('dev_work', true)}
        onPointerOut={handleMouse('dev_work', false)}
      />
      <mesh
        geometry={nodes.Dev_Work_Hitbox_Anim.geometry}
        material={whiteMaterial}
        scale={0}

        ref={devWorkAnimRef}
        position={[-1.298, 1.166, 1.75]}
      />
    </group>
  );
}

useGLTF.preload("/models/Dark Room/Dark_Targets.glb")
