/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 office-portfolio1-v1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/office-portfolio1-v1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Liljan_Single_Bathroom_Vanity.geometry} material={materials['AR3DMat Procedural Realistic Mirror.002']} position={[1.746, 0.506, -2.1]} rotation={[Math.PI / 2, 0, 0]} scale={1.144} />
      <mesh geometry={nodes.Plane011.geometry} material={materials['Car plastic dark']} position={[-1.587, 0.939, 1.774]} />
      <group position={[-1.86, 1.004, 1.809]} rotation={[0.147, 0, 0]} scale={[1.36, 1, 1]}>
        <mesh geometry={nodes.Plane033.geometry} material={materials['Stainless Steel']} />
        <mesh geometry={nodes.Plane033_1.geometry} material={materials['Stainless Steel']} />
        <mesh geometry={nodes.Aluminium003.geometry} material={materials['Plastic.001']} />
        <mesh geometry={nodes.BatteryIndicator.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Buttons001.geometry} material={materials.Keycaps} />
        <mesh geometry={nodes.Case.geometry} material={materials['Plastic.001']} />
        <mesh geometry={nodes.Case2.geometry} material={materials['Plastic.001']} />
        <mesh geometry={nodes.Case3.geometry} material={materials['Plastic.001']} />
        <mesh geometry={nodes.Feet.geometry} material={materials['Plastic.001']} />
        <mesh geometry={nodes.Feet2.geometry} material={nodes.Feet2.material} />
        <mesh geometry={nodes.Keycaps.geometry} material={materials.Keycaps} />
        <mesh geometry={nodes.LEDs.geometry} material={materials.LEDs} scale={1.252} />
        <mesh geometry={nodes.Lightspeed.geometry} material={materials.Keycaps} />
        <mesh geometry={nodes.Logo.geometry} material={materials.logo} />
        <mesh geometry={nodes.RubberFeet.geometry} material={materials.rubberfeet} />
        <mesh geometry={nodes.Screws.geometry} material={materials['Stainless Steel']} />
        <mesh geometry={nodes.Stabillizers.geometry} material={materials.switch_base} />
        <mesh geometry={nodes.Sticker.geometry} material={materials.Sticker} />
        <mesh geometry={nodes.Switch.geometry} material={materials.Sticker} />
        <mesh geometry={nodes.SwitchBase.geometry} material={materials['switch']} />
        <mesh geometry={nodes.SwitchBottom.geometry} material={materials.switch_base} />
        <mesh geometry={nodes.USB.geometry} material={materials['Stainless Steel']} />
        <mesh geometry={nodes.VolumeWheel.geometry} material={materials['Stainless Steel']} />
        <mesh geometry={nodes.VolumeWheelFrame.geometry} material={materials['Plastic.001']} />
      </group>
      <mesh geometry={nodes.Curved_Ultrawide_monitor_Black.geometry} material={materials['Steel damaged IOR.002']} position={[-1.589, 1.098, 1.569]}>
        <mesh geometry={nodes.Screen001.geometry} material={materials['screen.002']} />
      </mesh>
      <mesh geometry={nodes.desk.geometry} material={materials['LaminatedBoard_black.002']} />
      <mesh geometry={nodes.wall.geometry} material={materials['Wood Deck Black']} />
      <mesh geometry={nodes.rug.geometry} material={materials['90s Arcade Carpet']} position={[-1.486, 0.27, 1.638]} scale={[1.695, 1.329, 1.635]} />
      <mesh geometry={nodes.ground.geometry} material={materials['Material.006']} position={[1.985, 0, -4.357]} scale={[1.696, 1.696, 2.162]} />
      <mesh geometry={nodes.office_chair.geometry} material={materials['Plastic - Black']} position={[-1.602, 0.284, 2.641]} rotation={[Math.PI, 0, Math.PI]} scale={1.315} />
      <mesh geometry={nodes.couch.geometry} material={materials['Stripped Fabric Pillow']} position={[-1.628, 0.21, -2.364]} />
      <group position={[2.554, 1.173, 0.309]}>
        <mesh geometry={nodes.Vase_1.geometry} material={materials.Frond02_Mat} />
        <mesh geometry={nodes.Vase_2.geometry} material={materials.Ceramic} />
        <mesh geometry={nodes.Vase_3.geometry} material={materials.rete} />
        <mesh geometry={nodes.Vase_4.geometry} material={materials.Breanches} />
        <mesh geometry={nodes.Vase_5.geometry} material={materials.metallo} />
      </group>
      <group position={[-1.814, 3.157, -3.172]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Torus_1.geometry} material={materials.steel} />
        <mesh geometry={nodes.Torus_2.geometry} material={materials.Metal_Wire} />
        <mesh geometry={nodes.Torus_3.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/office-portfolio1-v1.glb')
